jwt.secretKey=N2E5OTJhMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWYwMTIzNDU2Nzg5YWJjZGVmMDEyMzQ1Ng==

jwt.access-token-expiration= 15m
jwt.refresh-token-expiration= 2d

razorpay.key_id=rzp_test_Sfc831soqG95Rm
razorpay.key_secret=s9WdjmkhfPQP64XZrRW6pA7H

geo.api.key=f3e98ca1cffc4f2f8d7e3e5413c9ac08