spring.application.name=VenueBookingSystem

spring.datasource.url=jdbc:mysql://localhost:3306/venueBookingSystem

spring.datasource.username=root

spring.datasource.password=welcome@123

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

server.port=8080

razorpay.key_id=rzp_test_Sfc831soqG95Rm
razorpay.key_secret=s9WdjmkhfPQP64XZrRW6pA7H

geo.api.key=f3e98ca1cffc4f2f8d7e3e5413c9ac08